### ISSUE TITLE
Credentials Confusion

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartoframes#1008]
This is related to #943

Consider this code:

```python
gc = Geocode(credentials=credentials)
ds = Dataset("SELECT 'Gran Via 46' AS address, 'Madrid' AS city")
gc.geocode(ds, street='address', city='city', country={'value': 'Spain'})
```

Note that I have passed credentials to Geocode but not to the Dataset.
Geocode credentials are intended to use the data services functions.

Now this used to work, because when geocode needs to upload the dataset it passes its own credentials to the upload method:

```python
input_dataset.upload(table_name=input_table_name, credentials=self._credentials, if_exists=if_exists)
```

But now I've changed geocode's implementation so it first tries to get the columns of the dataset,
which needs to perform a query, and it fails because the Dataset object doesn't have a context (no creds).

I'm not sure what would be the correct solution here

### Option 1.

require the dataset passed to `geocode` to have credentials:

```python
gc = Geocode(credentials=credentials)
ds = Dataset("SELECT 'Gran Via 46' AS address, 'Madrid' AS city", credentials=credentials)
gc.geocode(ds, street='address', city='city', country={'value': 'Spain'})
```

But then, when `geocode` calls `Dataset.upload` shouldn't it let it use the Dataset credentials, not its own?

EDIT: after some thought this kind of makes sense to me; the user has to define credentials for the query
so it can be executed if need be; then geocode uses the geocoding credentials to upload to temporary dataset;
now it would be nice if that could work with different credentials in both cases:
* Dataset credentials for one account where the query can be executed
* Geocode credentials for another account where the geocoding functions are executed and result tables are stored
But that won't work with the current implementation, because we execute the query and upload it in a single operation.
(it would work if we first downloaded query results, then uploaded to temp table etc.)

### Option 2.

Change the Dataset.get_column_names methods to accept optional credentials.

Having to pass credentials for any Dataset method that may need them seems tedious, isn't that what the Dataset credentials are for?

**Comment by oleurud** [comment]
We are not requiring credentials in the constructor in any case, including datasets from a CARTO table or query. 

Since a Dataset can be used in different ways and by different entities, I think you are right and credentials should be mandatory in table and query datasets. It should be done in the `create` method of both classes in a similar way than `_is_ready_for_upload_validation` or `_is_ready_for_dowload_validation` methods

**Comment by Jesus89** [comment]
Hi. After this PR: https://github.com/CartoDB/cartoframes/pull/1175 the Credentials param is mandatory when you are using a table or an SQL query, so it will throw an exception otherwise.

Is there anything we could clarify about this, or could we close the ticket? @jgoizueta

**Comment by jgoizueta** [comment]
If I understand correctly we're now in "Option 1" case, it is no longer possible to define a query (or table) dataset without credentials. This is nice since the problem mentioned with the geocoder is no longer possible.

Now there are places like [this one](https://github.com/CartoDB/cartoframes/blob/v1.0b4/cartoframes/data/services/geocoding.py#L508) where the geocoder passes its credentials to upload data that shouldn't be needed right?

There's also the question that it is possible to use different credentials for the geocoder and for its input data, and that won't work with the current implementation. Maybe we could check in the constructor that they're both from the same account and raise an exception otherwise.

**Comment by Jesus89** [comment]
Hi @jgoizueta, you're right. The "Option 1" is already solved since the Dataset needs the Credentials (for table|query) since the beginning.

The issue now is because we are using DataFrame and Dataset. The DataFrame is always local data, but the Dataset sometimes is local data (if it comes from a DataFrame) and other times is remote data (table|query). To fix the first case, I would add the credentials [here](https://github.com/CartoDB/cartoframes/blob/v1.0b4/cartoframes/data/services/geocoding.py#L504). For the second case (Dataset(query) vs Dataset(dataframe)) I would add the credentials only for the Dataset(dataframe) using the `if input_data.is_remote():` condition. What do you think?

I like the option to check both credentials (Geocoder and Dataset if provided) and raise an exception.

**Comment by jgoizueta** [comment]
I agree, if I understood correctly:

* If `input_data` is a dataframe then set `input_data = Dataset(input_data, self._credentials)`
* Else:
  + if `input_data.is_remote()` (i.e. query or table) then it must already have some credentials, let's check them; no credentials used for `input_data.upload()`
  + else (i.e. dataframe Dataset)  use `self._credentials` for the upload

Isolines may also have similar cases but I dare not take a look 😅

**Comment by Jesus89** [comment]
Exactly. Great pseudo-code :)

**Comment by Jesus89** [comment]
Hi @jgoizueta. I have refactored a bit of the Data Services using the new CartoDataFrame class and the new io functions. I think this is no longer an issue, but it would be nice if you could check the implementation before closing this one: https://github.com/CartoDB/cartoframes/pull/1130. Thanks!

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1130
