### ISSUE TITLE
Head and tails

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1033]
At the current version to check a dataset you have the following options:

1. Display on the map
2. Download and analyze

If the dataset doesn't have a geom we only have option 1.

### Dataset
That would be great to have dataset.head() and dataset.tail() for remote datasets. It will allow to explore the ehad and the tail without downloading the whole dataset. Example:

```python
dataset = Dataset('my_remote_table')
dataset.head()
dataset.tail()
```

### DO Catalog
It will be possible to get the head and tail of a dataset from DO (Only accessible if the user has previously licensed the dataset)

```python
dataset = Catalog.countries().iloc[0].datasets().iloc[0]
dataset.head()
dataset.tail()
```

**Comment by cmongut** [comment]
@alasarr could we close this issue? We already have the `head` and `tail` methods for datasets.

**Comment by Jesus89** [comment]
The `DO CatalogDataset` has head() and tail() methods, but no the `Dataset`. However, if we take into account this PR https://github.com/CartoDB/cartoframes/pull/1130, the CartoDataFrame, which replaces `Dataset`, has head() and tail() by default because it inherits from `GeoDataFrame`, we could consider this as solved.

**Comment by alasarr** [comment]
If CartoDataFrame does it, agree. But if not we still need for a `Dataset`

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1130
