### ISSUE TITLE
Add option to invert default Legend ordering

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1132]
As you can see in the following image, the order the legend is showing numbers is inverted. For some customers, users and team mates this is wrong.
![image](https://user-images.githubusercontent.com/711025/67768375-a42a2b00-fa52-11e9-8a1b-dcc3ef211d4d.png)

**Comment by makella** [comment]
I would definitely say this is a matter of personal preference!

Scroll through this google search for choropleth map and you'll see what I mean with the varying order of legends: https://www.google.com/search?q=choropleth+map+legends&source=lnms&tbm=isch&sa=X&ved=0ahUKEwitzp2YjsLlAhVKWxoKHVAxBxoQ_AUIEigB&biw=1920&bih=906

What I would like to think about is if this should be a flip parameter vs. actually making all of the legends read max-min. The reason I say this is because if you think of different orientations and legend types, we don't have a one rule fits all kind of situation.

For example, in the size continuous legend, having the order go from max to min would give us another legend that people would not really like and one that people would feel is "wrong"... imagine this the opposite way:

![Screen Shot 2019-10-29 at 12 46 32 PM](https://user-images.githubusercontent.com/1566273/67799025-3aa61e80-fa4a-11e9-90c2-7125b5d0a0ab.png)

Also, if you are mapping a variable where low to high is more logical for the ordering of the legend, that, I think is an important factor to keep in mind. 

Anyway, instead of making a global change, can we think about adding a parameter for this? Which would basically reverse the order of values returned to the legend and give users an option to choose what they think fits best for their map?

Just a few examples from the google search above (you'll see that **a lot** of maps go from l>h like we have):
![Screen Shot 2019-10-29 at 12 40 35 PM](https://user-images.githubusercontent.com/1566273/67798569-5f4dc680-fa49-11e9-83a7-847eb90e9e53.png)
![Screen Shot 2019-10-29 at 12 40 12 PM](https://user-images.githubusercontent.com/1566273/67798582-6379e400-fa49-11e9-9a38-e9751f38cf52.png)
![Screen Shot 2019-10-29 at 12 39 54 PM](https://user-images.githubusercontent.com/1566273/67798594-6a085b80-fa49-11e9-8908-66c0e4c3010e.png)

**Comment by cmongut** [comment]
Totally agree! Thanks for the input @makella!

Let's do that, when we tackle this, let's add a parameter to be able to change the order.

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/carto-vl/pull/1429, https://github.com/CartoDB/cartoframes/pull/1537
