### ISSUE TITLE
version of ipywidgets?

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#1152]
Hi I think the current cf is using `ipywidgets` now (https://github.com/CartoDB/cartoframes/issues/1111). And wondering where I can find the version info of it? I installed this lib long time ago and here's the conflict I have in my local env (`ipywidgets: '7.4.2'`). just wanna make it clear which version I should upgrade to? 

<img width="753" alt="Screen Shot 2019-11-04 at 2 40 50 PM" src="https://user-images.githubusercontent.com/13675438/68153735-0b912080-ff14-11e9-9646-b5641e502750.png">

**Comment by djfan** [comment]
Upgrading to `7.5` makes it work. but better to add it to setup? 
`ipywidgets` didn't upgrade to `7.5` as I upgraded cartoframes to`b4` .

**Comment by Jesus89** [comment]
Hi Dongjie! Thanks for the feedback!

I'm not sure if we should add this as a dependency of CARTOframes since it's attached to the jupyter notebook cc @andy-esch.

However, for the 1.0 we want to use custom templates instead of `ipywidgets`, so we won't need this dependency anymore (https://github.com/CartoDB/cartoframes/issues/1111)

**Comment by andy-esch** [comment]
I agree it'd be best to avoid having ipywidgets as a dependency

**Comment by djfan** [comment]
sounds good to me if this is only a temporary thing. feel free to close this issue. 😄
