### ISSUE TITLE
[DO - enrichment] Unification proposal

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1185]
This proposal tries to group the three different enrichment methods into one. (The enrichment method by ID hasn't been thought yet and I am assuming we don't need the data_geom_column param anymore).

```
enrich_points(data, variables, filters={}, credentials=None)
```

```
enrich_polygons(data, variables, agg_operators={}, filters={}, credentials=None)
```

```
enrich_ids(data, variables, from_column, to_column, filters={}, credentials=None)
```

As we can see, the following params are shared between the different methods:
**data, variables, filters and credentials.**

And the ones that are not shared are: **agg_operators, from_column and to_column.**

Knowing this, we could try to have only one interface like this one:

```
enrich(data, variables, agg_operators={}, from_column=None, to_column=None, filters={}, credentials=None)
```

*If we move to a CartoDataFrame, maybe the enrich method should belong to it (as other methods).

Thoughts? 

cc @oleurud  @alasarr

**Comment by alasarr** [comment]
Not sure, I think we'll end with a huge method with lots of parameters quite difficult to explain. I suggest keeping it separated and once we have a clear vision of how the final doc will look like we can consider the merge

>*If we move to a CartoDataFrame, maybe the enrich method should belong to it (as other methods)

Nope, because a DataFrame (not CARTODataFrame) could be the input of enrichment by id. So, we need to keep the enrich separated and I don't like the idea to give two methods to do the same thing.

**Comment by oleurud** [comment]
My opinion as a developer: I don't see a real win merging into one method, because anyway I will need to know if I am working with points or polygons to bring the proper parameters. 

Furthermore, the lib would need to detect the case. So, I prefer the current case because it is simpler.

**Comment by cmongut** [comment]
👌 Thanks guys!
