### ISSUE TITLE
Installation: Is the pyproj==2.2.2 pin needed?

### ISSUE THREAD

**Issue by jorisvandenbossche** [CartoDB/cartoframes#1203]
Current the pyproj dependency is pinned to a very exact version:

https://github.com/CartoDB/cartoframes/blob/de0f514a8460d61a86afd58e46f7e738060ba09a/setup.py#L34

Wondering if the pin is actually needed? I general such specific pins make installing more annoying than needed (eg if you already have another version of pyproj installed) 
I didn't directly see any reason for the pin mentioned in the commit (https://github.com/CartoDB/cartoframes/commit/f51c23eb9f0dfdab8f46b31ff4fc1fd65cd149d5) or its related PR.

**Comment by Jesus89** [comment]
Hi @jorisvandenbossche!

There was an issue in CI with our tests in Python3 (9 days ago): https://travis-ci.org/CartoDB/cartoframes/builds/608380323?utm_source=github_status&utm_medium=notification. The only solution then was to fix the version of pyproj to the 2.2.2 because this worked in both Py2 and Py3. It seems that exactly 9 days ago pyproj was releasing a new version, so maybe it was related to that.

I agree is not a good practice at all, in this case, it was just a hotfix. I have run the tests again without it and it seems to work. So we can remove it from the setup.py file.

Thanks for the observation :)

**Comment by jorisvandenbossche** [comment]
@Jesus89 ah, you were running into this problem: https://github.com/pyproj4/pyproj/issues/477 
Summary: with pyproj 2.4.1, they initially only build manylinux2010 wheels. But to install those, you need a recent version of pip (>= 19, on travis you are using pip 18.1). So updating pip in travis.yml before doing other installations could solve that. Now, in the meantime, the older format manylinux1 wheels were uploaded again, and so also with the older pip version, installation should be fine again.

**Comment by jorisvandenbossche** [comment]
Let's see what travis says now ;) -> https://github.com/CartoDB/cartoframes/pull/1205

**Comment by Jesus89** [comment]
Hey. Thanks for the explanation of the issue. It seems that Travis is happy now :rocket:

**Comment by Jesus89** [comment]
Closed in https://github.com/CartoDB/cartoframes/pull/1205
