### ISSUE TITLE
Handle the case when a CatalogDataset summary is not provided

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1208]
https://docs.google.com/document/d/1qMdKnvP0uv0nWpFJ0GX0qaom0pkmwUxiVp_ZgFK07Hw/edit#

@xavipereztr could you review the doc?

**Comment by xavipereztr** [comment]
Hi @cmongut 

Why should we be making the distinction for the two cases in which we do not have "Summary" metrics? The bottom line for the end-user is that the Summary information is not available...so we can simplify it and have a common path for both cases, rather than us having to provide unnecessary reasoning/explanations to the end-user w/o knowing her specific case.

**Comment by cmongut** [comment]
It makes sense. I provided both ways because you were adding that information in the metadata.
