### ISSUE TITLE
blank popup showing for a second layer with no popup defined

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#1254]
hello!

I have two Layers in a Map and I have popups defined for the top point Layer but not the second, polygon Layer. When I hover over the second Layer in the map, I'm seeing blank popup windows:

![popup-blank](https://user-images.githubusercontent.com/1566273/69676975-1e080100-105f-11ea-8fd7-affad7670dac.gif)

Example code to try for debug:

```
from cartoframes.auth import set_default_credentials
from cartoframes.viz import Map, Layer, Popup

set_default_credentials('cartoframes')

Map([
    Layer(
        'countries_africa',
    ),
    Layer(
        'global_power_plants','width:15',
         popup=Popup({
            'hover': ['$fuel_type']
        })
    )
],viewport={'zoom': 3.69, 'lat': 6.436720, 'lng': 30.492547})
```

**Comment by oriolbx** [comment]
I experienced the same problem when in one of the layers I defined a click popup and in the other has a hover popup.

It looks like this issue is not happening when both layers have the hover popup set.

### Case 1: Two layers with hover popup

Overlapped areas between the two layers show a popup with popup values from both layers

```python
Map([
    Layer(
        iso_cdf,
        widgets=[
            formula_widget(
                'popcy',
                'sum',
                title='Total Population Served'
            ),
            formula_widget(
                'inccymedhh',
                'sum',
                title='Median Income ($)'
            ),
            formula_widget(
                'lbfcyempl',
                'sum',
                title='Employed Population',
            ),
            formula_widget(
                'educybach',
                'sum',
                title='Number of People with Bachelor Degree',
            ),
            category_widget(
                'id_store',
                title='Store ID'
            )
        ],
        popup=Popup({
            'hover': {
                'title': 'Store ID',
                'value': '$id_store'
            }
        })
    ),
    size_continuous_layer(
        stores_cdf,
        'revenue'
    )
])
```

![Screenshot 2019-12-17 at 15 35 25](https://user-images.githubusercontent.com/11177693/71004911-f5fe4180-20e2-11ea-8679-92d262b239f6.png)

### Case 2: One layer with hover popup and the other layer is set with a Click popup

```python
Map([
    Layer(
        iso_cdf,
        widgets=[
            formula_widget(
                'popcy',
                'sum',
                title='Total Population Served'
            ),
            formula_widget(
                'inccymedhh',
                'sum',
                title='Median Income ($)'
            ),
            formula_widget(
                'lbfcyempl',
                'sum',
                title='Employed Population',
            ),
            formula_widget(
                'educybach',
                'sum',
                title='Number of People with Bachelor Degree',
            ),
            category_widget(
                'id_store',
                title='Store ID'
            )
        ],
        popup=Popup({
            'click': {
                'title': 'Store ID',
                'value': '$id_store'
            }
        })
    ),
    size_continuous_layer(
        stores_cdf,
        'revenue'
    )
])
```

Blank popup when moving mouse over geometry set with click popup.

![Screenshot 2019-12-17 at 15 38 40](https://user-images.githubusercontent.com/11177693/71005221-8d639480-20e3-11ea-9489-551e00d5cf02.png)

Blank popup disappears when you a click with the mouse on the geometry to display the click popup:

![Screenshot 2019-12-17 at 15 38 45](https://user-images.githubusercontent.com/11177693/71005227-8fc5ee80-20e3-11ea-82ee-7c78e6291b35.png)

**Comment by elenatorro** [comment]
It seems to be fixed with the last Popup changes, please reopen the issue if it happens again 👍
