### ISSUE TITLE
Enrichment and dataframes

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1255]
- [ ] A Pandas DataFrame is accepted, we shouldn't allow it. The input of geospatial data at CF should always be an instance of GeoDataFrame. Since a GeoDataFrame is provided the param `geom_column` is not required anymore.  

- [ ] If a geodataframe is provided with a column that's not `geometry` enrichment fails. We should check the default `geometry` column of the data. Should be fixed with previous point  

- [ ] Enrichment method doesn't return a CartoDataFrame it returns a GeoDataFrame

**Comment by Jesus89** [comment]
I agree we should provide the same API for Enrichment and Isolines.

A GeoDataFrame doesn't necessarily have a geometry column, so the `geom_colum` could be necessary even for a GeoDataFrame.

The two options are:
- Allow only GeoDataFrames with a valid geometry column
- Allow any DataFrame (or GeoDataFrame with/without geometry) + `geom_col` param

IMO, we should allow the second one because is more generic and provides a clear way to use the API. Let's take a look at this example:

```py
# The user loads a CSV of a CARTO table (with the_geom column)
df = pd.read_csv('...')

# This doesn't work because you need to decode the column
# gdf = GeoDataFrame(df, geometry='the_geom')

# So a CartoDataFrame must be used in this case
cdf = CartoDataFrame(df, geometry='the_geom')

result = Enrichment(credentials).enrich_points(cdf, ...)
```

On the other hand, if we allow passing "geom_col" this operation is easier for the user:

```py
# The user loads a CSV of a CARTO table (with the_geom column)
df = pd.read_csv('...')

result = Enrichment(credentials).enrich_points(df, geom_col='the_geom')
```

**Comment by Jesus89** [comment]
Closed via https://github.com/CartoDB/cartoframes/pull/1270
