### ISSUE TITLE
Test CartoDataFrame

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartoframes#1260]
CartoDataFrame inherits from geopandas.GeoDataFrame.

At the following issue https://github.com/CartoDB/cartoframes/pull/1130#issuecomment-557695873 we've talked about some caveats that could end losing the instance of CartoDataFrame in favor of GeoDataFrame.

@Jesus89 implemented some fixes at https://github.com/CartoDB/cartoframes/issues/1236. The idea of this issue is to try to find other cases where this is actually happening

**Comment by jorisvandenbossche** [comment]
Some additional cases I mentioned in https://github.com/CartoDB/cartoframes/pull/1130#issuecomment-557695873 (and some others):

- Selecting columns or selecting rows (with something else as a boolean series) with getitem (`cdf[..]`)
- `pd.concat`, merge/join, astype
- spatial join, spatial overlay
- dissolve, explode

**Comment by alasarr** [comment]
Thanks a lot @jorisvandenbossche

**Comment by alejandrohall** [comment]
Hi all!

I have been testing the class _CartoDataframe_ in order to find some operations that return a GeoDataframe or DataFrame and lead to you to lose the reference to the CartoDataFrame class, and I have found some of them.

There are some operations that in terms could make sense that return to you a pandas DataFrame (like .describe() maybe) but there are other operations that make sense that should return to you a CartoDataFrame but returns a GeoDataFrame or DataFrame instead. 

In the following link, you can find the notebook I used to test all the cases:
https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/alejandrohall/ecf925767ee5f757672285cd10e10db3/raw/417ab921a38b126df49df5f07784120ee03cc2e0/test.ipynb

cc: @alasarr @Jesus89 @jorisvandenbossche

**Comment by Jesus89** [comment]
Thanks @jorisvandenbossche for the information! I have covered the cases you mention in this branch: https://github.com/CartoDB/cartoframes/pull/1265.

Awesome testing @alejandrohall! I will run your notebook in that branch to see if something is already covered there.

**Comment by Jesus89** [comment]
I have tested your notebook. The case of filtering by list, ndarray and Series is fixed, also the astype, merge, dissolve and explode.

I agree that  `.describe()` (and `to_frame()` maybe) should return a DF.

**Comment by jorisvandenbossche** [comment]
Something I also noted in  #1265, in geopandas we deliberately do not return a GeoDataFrame if the result of the operation does no longer contains the geometry columns (eg selecting multiple columns but not the geometry column, `astype` where the geometry column gets converted to eg text, ...)

**Comment by Jesus89** [comment]
Yes. I also noticed that. It's something we need to think about because a user can upload data without geometry to CARTO, so in this case, it could make sense to return a CDF after a CDF.astype('object') operation, for example, but we need to think about it.

**Comment by jorisvandenbossche** [comment]
>  a user can upload data without geometry to CARTO

For me, that's another reason to consider the functional/accessor/pandas-flavor approaches I mentioned in https://github.com/CartoDB/cartoframes/pull/1130#issuecomment-557695873. 
For example, when registering an accessor with pandas, it automatically will be available on both DataFrame / GeoDataFrame, and a user can use the same functionality to upload data to CARTO regardless of whether they have a DataFrame or Carto/GeoDataFrame. The same can be said for the other (non-subclass) approaches.

Note that returning a GeoDataFrame/CartoDataFrame even when there is no longer a geometry column can be quite annoying for the user. Because geopandas (and thus also CartoDataFrame) overrides some functionality of the base pandas DataFrame. 
Concrete example: you select some columns (other than the geometry column) and then want to plot them. If this still is the Geo/CartoDataFrame instead of a normal DataFrame, the plot method is still the one of geopandas and not the one of pandas, and thus plotting will not work as the user expects.

**Comment by Jesus89** [comment]
:+1: We will take all this information into account. Our immediate plan is to close a beta release to enable DO features to some beta clients. After that, we will review all the options for DataFrame / GeoDataFrame integration.

**Comment by alasarr** [comment]
>If this still is the Geo/CartoDataFrame instead of a normal DataFrame, the plot method is still the one of geopandas and not the one of pandas, and thus plotting will not work as the user expects.

Good point

**Comment by Jesus89** [comment]
Hi @alasarr, regarding the `plot` method, I have added a wrapper in the CDF so it works as expected in any case: https://github.com/CartoDB/cartoframes/pull/1339.

**Comment by Jesus89** [comment]
We have completed the tests, so we can close this ticket.

**Comment by jorisvandenbossche** [comment]
There are some other methods as well that GeoPandas overwrites which assume there is a geometry column (eg merge, explode).

**Comment by alasarr** [comment]
Thanks @jorisvandenbossche for reporting! @Jesus89 could you add it for the next iteration?

**Comment by Jesus89** [comment]
Closing this because we are going to implement a functional approach for this release.
