### ISSUE TITLE
Visualization API research

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartoframes#1301]
## Proposal

**UPDATED**

Based on the information provided in this thread, I add here the final conclusions:
- Add Style helpers (from Layer helpers, in cartoframes.viz.styles)
    - basic_style
    - color_bins_style
    - color_category_style
    - color_continuous_style
    - size_bins_style
    - size_category_style
    - size_continuous_style
- Add default UI component helpers
    - default_legend
    - default_widget
    - default_popup
- Allow legends/widgets/popups=True/False to enable the defaults to the Layer
- Add title, description, footer to the Layer
- Refactor Layer helper methods? Should we remove them?

```py
from cartoframes.viz import Layer, size_continuous_style

Layer(
    source='starbucks_points',
    style=size_continuous_style(
        value='revenue',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80]
    ),
    legends=True,
    title='Revenue $'
)
```

```py
from cartoframes.viz import Layer, size_continuous_style, default_legend

Layer(
    source='starbucks_points',
    style=size_continuous_style(
        value='revenue',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80]
    ),
    legends=[
        ....,
        default_legend(title='Revenue $'),
        ....
    ]
)
```

**Comment by makella** [comment]
Below are some initial thoughts/ideas on how we can unify our current visualization patterns. The first section talks about enhancements needed to the style class of the Layer to remove the dependency on VL syntax and the second section (thematic maps) focuses on how we can 1) extend current viz layer helpers to be more flexible in widgets and popups and 2) how we can make the cartographic thinking we've built into the helpers easily accessible in the Layer

## _Non-thematic_ maps
These maps are ones where users aren't symbolizing an attribute in their data but simply symbolizing a dataset where all features are equal. Whether to modify the defaults or present the results of an analysis, these maps are currently not served by our viz layer helpers and in order to make, a user has to know VL syntax. This will also eliminate the styling confusion (`strokeWidth: / width=` and `width: / size=`, etc.) that a user needs to know in our current implementation.

In this case, we will assume the user will add their own Legend, Widgets and Popups so the main thing here is to simplify how the Style is defined.

### Example proposal:
Add table to a Layer and get default symbology:
```
Layer ('starbucks_points')
```
Modify/customize a basic style:
```
Layer(
  'starbucks_points',
  style=(
    color= 'green',
    size= 5,
    opacity= 0.5,
    stroke_width= 1,
    stroke_color= 'purple'
  )
)
```
To discuss:
- We would need to slightly modify the 'default legend' to help users make a complete map with this simple style as described in this ticket: https://github.com/CartoDB/cartoframes/issues/1192

Related tickets:
- https://github.com/CartoDB/cartoframes/issues/927


## _Thematic_ Maps
This is when a user wants to symbolize on a numeric, categorical, or time-based attribute. In this case, with our current implementation, a user can use a viz layer helper but if they have started their workflow at the Layer level and added other components like Widgets and Popups, they have to in essence start from scratch. In addition, our current implementation of the viz layer only supports mapping and adding related components for _one attribute_ (except in the case where a user chooses to animate by another attribute using the option `animate='attribute_name'`).

Therefore, the workflow for a thematic maps should not be limited to only one attribute and through our discussions there are two potential paths to make this kind of map both of which we should address.

### Path 1: Use a viz layer helper
From our internal research, what we have seen is that viz layer helpers are too limited in their offerings. Specifically with regards to Widgets and Popups in the cases where users want to add additional information to the map to support their analysis.

For this path, we would add the ability to add more/different Widgets and Popups. The Legend would be the same default that we provide as part of the benefit of using a viz layer is to get default cartography which the Legend is an important part of. 

We should discuss the different options for this to happen...one way is for the viz layers to accept additional information using the popup and widget classes inside of the helper layer definition. The benefit of this is if a user is working at the Layer level and already has popups and widgets defined, that they could easily switch the Layer to something like `size_continuous_layer` and not lose all of that other work. 

The thinking here is what @elenatorro [has tested](https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/viz/helpers/utils.py#L18-L20) and looks like:

```
size_continuous_layer(
        geo_cdf,
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80],
        popup=Popup({
            'hover': [{
                    'title': 'Address',
                    'value': '$address'
                }, {
                    'title': 'Precision',
                    'value': '$gc_status_rel'
                }, {
                    'title': 'Revenue',
                    'value': '$revenue'
                }]
        })
    )
```

To discuss:
- As previously mentioned, for me, providing an appropriate legend by default is an important part of the visualization therefore, I would keep the current legend pattern we have where we add the appropriate one and provide the user the option to add a title, description and footer.
- If, for example, no popups are defined with the popup class, would a user still be able to take advantage of the helper's default popup? I was thinking something like `default_popup=True` if set, you get our default popup and if not, you can add your custom popups with the popup class and same for the widgets. Should we think about the same thing for legends? We provide a default legend but if the user wants to take advantage of the Legend API and sets `default_legend=False` what would happen with the `title`, `footer` and `description` parameters if already set?
- To make this the most user-friendly, the proposal to [unify legend/widget/popup apis](https://github.com/CartoDB/cartoframes/issues/1300) would be important for this to happen

### Path 2:  Make a thematic map at the Layer
The second way a user could make a thematic map is to stay inside the default Layer. Currently, this requires even more advanced VL syntax (ramps, etc.) and the biggest issue is that people are missing out and not able to take advantage of the built-in thinking as a tradeoff for more control with widgets and popups.

In this case, we could use the `style` class to bring in all the _style-related_ parameters from the helpers and continue with the pattern where users could use the legend/widget/popup apis to add the other components to the map.

In essence, this would be a blend of the previous 2 examples: 

```
Layer(
    'starbucks_points',
    style=size_continuous(
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80]
    ),
    legend=Legend(
        'size-continuous',
        title='Revenue',
        description='description',
        footer='footer'
    ),
    popup=Popup({
        'hover': [{
            'title': 'Address',
            'value': '$address'
        },{
            'title': 'Precision',
            'value': '$gc_status_rel'
        },{
            'title': 'Revenue',
            'value': '$revenue'
        }]
    }),
    widgets=[
        formula_widget(
        'count',
        title='Number of Stores',
        description='description'
    )]
)
```
Look forward to discussing these ideas together!

cc @elenatorro @Jesus89 @cmongut

**Comment by Jesus89** [comment]
Awesome @makella!!

This is really valuable research! I like the way you simplify and unify the Layer API, it's definitely better and easier for the user. I'll think about default UI components related to the style helpers.

Btw, this PR is also related https://github.com/CartoDB/cartoframes/issues/1300.

**Comment by elenatorro** [comment]
Nice work! I'd also like to discuss the following regarding **popups** and **legends**:

- Popups: We're still using dicts, and this is an inconsistency. We've talked in the past about having popup helpers. For instance:

```py
popup=[
    hover_popup('address', title='Address'),
    hover_popup('gc_status_rel', title='Precision'),
    hover_popup('revenue', title='Revenue')
]
```

- Legends: add legend helpers as well:

```py
legend=[
    size_continuous_legend(title='Revenue', description='description', footer='footer')
]
```

The result would be something like:

```py
Layer(
    'starbucks_points',
    style=size_continuous(
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80]
    ),
    legend=[
        size_continuous_legend(title='Revenue', description='description', footer='footer')
    ],
    popup=[
        hover_popup('address', title='Address'),
        hover_popup('gc_status_rel', title='Precision'),
        hover_popup('revenue', title='Revenue')
    ],
    widgets=[
        formula_widget('count', title='Number of Stores', description='description')
    ]
)
```

**Comment by Jesus89** [comment]
Hi @elenatorro there is a proposal regarding that in #1300.

**Comment by elenatorro** [comment]
omg it's true! I perfect, we can tackle this in the issue 👍

**Comment by cmongut** [comment]
Team, really nice research :) This need comes for current users so it will be really valuable.

Let's continue with the conversation.

- Why are you using the `style` key in the `Layer` class but not in the visualization layer?
- What about going only for the path 2 for thematic maps? Could the user set popups=True, widgets=True at the layer level? I know this option can be more complex but I don't know if we can think of a solution. Maybe instead of using a style helper we could you a keyword, something like:

`Layer(
    'starbucks_points',
    style={
        'type': 'size_continuous',
        'variable': 'revenue',
        'title': 'Revenue $',
        'color': 'white',
        'opacity': '0.2',
        'stroke_color': 'blue',
        'size': [20, 80]
    ),
    legend=True,
    popups=True,
    widgets=True
)`

**Comment by makella** [comment]
@Jesus89 regarding the actions related to the default components of the style helpers, here are some notes/thoughts that @elenatorro and I discussed:

Let's say you use the size continuous layer:
```
size_continuous_layer(
        geo_cdf,
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80]
)
```
By _default_ the user will get:
- a styled map on `revenue`
- with the size continuous legend on `revenue` with the title `Revenue $`
- a hover popup on `revenue` with the title `Revenue $`
- the histogram widget off by default
- if `animation` parameter is set, a time-series widget

The user will then have the following _options_ to overwrite the defaults related to popups, widgets, legends:

**Popups**:
- to deactivate popups, the user can set `popup=False` this will disable the default popup we provide
- if the user wants to customize, they can use the same popup parameter with their custom definitions for example:
```
size_continuous_layer(
        geo_cdf,
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80],
        popup=[
          click_popup('address', title='Address'),
          hover_popup('gc_status_rel', title='Precision')
       ]
)
```
- in this case the `title=` parameter would only be assigned to the Legend

**Widgets**:
- currently, widgets are `False` by default so if a user does not want the default widget, no action is needed
- if the user wants to turn on the helper's widget, they can set `widget=True`
- if the user wants to customize widgets, they can use the same widget parameter to customize. For example:
```
size_continuous_layer(
        geo_cdf,
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80],
        widget=[
            formula_widget('count', title='Number of Stores', description='description'),
            category_widget('store_name', title='Store Name')
        ]
)
```
- Question here: if `animate=` is set, then a user will get a time-series widget by default. What should the pattern be? For example, if a user overwrites the widget parameter with a custom definition, should the time-series widget be turned off as well?  

**Legends**
- to deactivate the default legend, the user can set `legend=False` 
- if the user wants to customize, they can use the same legend parameter with their custom definition for example:
```
size_continuous_layer(
        geo_cdf,
        'revenue',
        title='Revenue $',
        color='white',
        opacity='0.2',
        stroke_color='blue',
        size=[20, 80],
        legend=[
            size_bins_legend(title='Revenue', description='description', footer='footer')
       ]
)
```
Questions:
- in this case what would happen with the `title=`,`description` and `footer` parameters?

**Comment by makella** [comment]
@cmongut great!

I too like the option for one path... I added both paths so we could consider which one to go with based on the level of effort and time we would have to complete...

@elenatorro and I spoke about this in more detail today and both also like the idea of providing only one way to make maps. there are some other things we should discuss moving forward but in regards to your proposal, here are some thoughts/notes from our discussion.

Basically, with this implementation, what we would need to do is have the Layer read the definition of each style helper: this includes the style and the associated defaults related to Legends, Widgets and Popups.

Here is an outline of how we see this working:

#### Default behavior
Provides:
  - styled map
  - provides Legend (with parameters for title, description, footer)
  - provides popup on hover
  - option to "turn on" widget on mapped attribute
```
Layer(
    'starbucks_points',
    style=(
        type= 'size_continuous',
        value= 'revenue'
    )
)
```
To discuss:
  - one thing @elenatorro was mentioning here is if we, by default, should have all three components (legend, widget, popup) set to `True` to make the options more consistent. Let's definitely discuss this as I agree with her. From my perspective, we should always have the Legend draw to help interpret the map but maybe we should consider having both popups and widgets be an option that users turn on.

#### Customizations
- this would include the same style-related parameters available with current helpers
- other components can be customized in two ways:
  1) set to `True` to turn "on" set to `False` to turn "off"
  2) or customize components by class
For example, the map below would have a custom style, default legend, no popups and custom widgets:
```
Layer(
    'starbucks_points',
    style=(
        type= 'size_continuous',
        value= 'revenue',
        title= 'Revenue $',
        color= 'white',
        opacity= 0.2,
        stroke_color= 'blue',
        size= [20, 80]
    ),
    popups=False,
    widgets=[
            formula_widget('count', title='Number of Stores', description='description'),
            category_widget('store_name', title='Store Name')
    ]
)
```
To discuss:
- similar to my questions above, 
    - what happens in the case where `animate` is set but custom widgets are defined? currently, if a user animates they get a time-series widget by default
    - if Legends and Popups are set to `False`, what happens with parameters `title, description, footer`?

**Comment by cmongut** [comment]
@Jesus89, it's looking great!

- Could you add to the example all the style options we will have available? Maybe `stroke_with` is missing.

- About removing the helpers methods, I would do it. The new way would be:

```
from cartoframes.viz import Layer, size_continuous_style

Layer('starbucks_points', size_continuous_style('revenue'), legends=True, popups=True)
```

@andy-esch could you review this proposal?

**Comment by elenatorro** [comment]
About removing the layer helpers, I would not remove them entirely. Removing them will mean doing a big breaking change, but I agree we should not support both ways of doing this.

Let's keep the helpers, but remove them from documentation. This way, people migrating from the beta won't have breaking changes. And, at some point, we will announce we will remove them.

**Comment by elenatorro** [comment]
We will tackle this last point in the *Layers Helpers* issue https://github.com/CartoDB/cartoframes/issues/1350 I'm closing this one, but feel free to comment anything 👍

**Comment by cmongut** [comment]
Hey @elenatorro, I like the idea to keep the helpers if we can, let's see how long.

About the Layer class, have you thought about doing something similar or we will have breaking changes for sure?

**Comment by elenatorro** [comment]
You're right, it also has some breaking changes. Let's discuss if we keep them in the issue I mentioned once if finish the rest of the issues 👍 thanks!
