### ISSUE TITLE
Cartoframes maps are not being rendered in Medium

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1333]
It may be caused by some redirection.

![CF_map_error 2](https://user-images.githubusercontent.com/711025/70549853-2d19a380-1b75-11ea-918c-014a17757491.gif)

**Comment by Jesus89** [comment]
cc @CartoDB/rt-managers

**Comment by alrocar** [comment]
I've been looking into this issue. It seems Medium uses a third party service to embed anything.

For the case of Kuviz it's doing a request to this service:

```
https://cdn.embedly.com/widgets/media.html?url=https://public.carto.com/kuviz/f8dcf0ef-45e5-4578-a245-af443c870ffa&src=https://public.carto.com/viz/f8dcf0ef-45e5-4578-a245-af443c870ffa/embed_map&type=text/html&key=a19fcc184b9711e1b4764040d3dc5c07&schema=carto
```

There are two parameters `url` and `src` with different values. The error 500 comes because in the end the `iframe` in medium is created with the `src` value, instead of `url` which is the correct one.

I don't know from where it comes the `src` param... maybe they are doing a get request to some of our APIs.

In any case, I'd like to prioritize in RT only enterprise issues. Could we tackle this issue as part of the upcoming `kuviz in the dashboard` project?

Thanks!

**Comment by gonzaloriestra** [comment]
As @alrocar said, the problem comes from [embed.ly](embed.ly).

They have an API to extract information from an URL, and they are returning the wrong `src`:
https://embed.ly/docs/explore/extract?url=https://public.carto.com/kuviz/f8dcf0ef-45e5-4578-a245-af443c870ffa

I guess they have a rule to convert the CARTO URLs to `/embed_map`, and that doesn't work for kuviz.

There's no quick workaround because [Medium does not allow to embed custom HTML](https://help.medium.com/hc/en-us/articles/214981378-Embeds). 

I'll try to add a redirection from `/embed_map` for kuviz to fix it from our side. It's a simple change and I think it should work.

Another alternative could be to talk with embed.ly, where [we are already providers](https://embed.ly/provider/cartodb), to ask for a custom behavior for kuviz URLs, by [email](mailto:support@embed.ly) or [web form](https://embed.ly/providers/new). Also, we should ask them to update our name and logo.

**Comment by gonzaloriestra** [comment]
Fixed with the redirection.
