### ISSUE TITLE
Epoch time in animation widget when source is a CartoDataFrame 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1358]
* This behaviour was reproduced with beta 5 and beta 6 of CARTOFrames.

When creating a map from a dataframe with a timestamp or date format, the animation widget shows the time as epoch time instead of the date format of the dataframe or CartoDataFrame:

![Screenshot 2019-12-13 at 11 33 27](https://user-images.githubusercontent.com/11177693/70793801-6f70f980-1d9c-11ea-922e-e1dfc4f3aedc.png)

And the result of the widget of the map is the next one:

![Screenshot 2019-12-13 at 11 24 36](https://user-images.githubusercontent.com/11177693/70793753-4fd9d100-1d9c-11ea-903d-06234c0cdb04.png)

**Comment by elenatorro** [comment]
After some research, I think there're two ways of solving this issue. To bring some context, the problem we're facing here is that when using a DataFrame, it converts the data to a GeoJSON source, and therefore we're not detecting which columns are dates. The CARTO VL way of doing this is by setting as source options which columns have date format, for instance:


```js
const source = new carto.source.GeoJSON(myData, { dateColumns: ['date_column'] });
```

**Option 1:**

The first option is to add a parameter to the Layer class (or to the `style` helpers, depending on what we decide if we go for this option) to tell CARTOframes the date columns manually

```python
data = {
    'date_column': ['2019-11-10', '2019-11-11', '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15'],
    'lon': [50, 40, 30, 50, 30, 40],
    'lat': [0, 1, 2, 3, 2, 1]
}

df = pd.DataFrame(data)
gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.lon, df.lat))

Map(
    Layer(
        gdf,
        style=animation_style('date_column', color='blue', size=20, duration=20),
        widgets=animation_widget(title='Date'),
        date_col='date_column'
    )
)
```

**Option 2:**

Detect internally which columns are dates. However, in this case the above example wouldn't work because `date_column`'s type is **string**. In order to make it work, this column type should be **datetime**:

```python
data = {
    'date_column': ['2019-11-10', '2019-11-11', '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15'],
    'lon': [50, 40, 30, 50, 30, 40],
    'lat': [0, 1, 2, 3, 2, 1]
}

df = pd.DataFrame(data)
df['date_column']= pd.to_datetime(df['date_column']) 
gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.lon, df.lat))

Map(
    Layer(
        gdf,
        style=animation_style('date_column', color='blue', size=20, duration=20),
        widgets=animation_widget(title='Date')
    )
)
```

Which option would you go for?

cc @makella @cmongut @Jesus89

**Comment by makella** [comment]
after speaking with @elenatorro i think that option 2 makes the most sense since it is using a built-in dataframe conversion method

**Comment by elenatorro** [comment]
Fixed!

**Comment by jdgodchaux** [comment]
Hi @elenatorro !! Awesome job! I have a client who ran into this issue and want to let them know this has been solved, but want to set expectations appropriately. Will this be update in the next CARTOframes release?

**Comment by Jesus89** [comment]
Hi @jdgodchaux. Yes, this will be included in the next release (on Friday).

**Comment by jdgodchaux** [comment]
Awesome thank you @Jesus89 !!
