### ISSUE TITLE
if using `cc.map` in python or ipython repl, save map images to local directory

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#142]
Related to #140

**Comment by ljwolf** [comment]
For this, would we be shooting for something to do if `interactive=False` at [l657](https://github.com/CartoDB/cartoframes/blob/master/cartoframes/context.py#L657)?

If so, I think using `matplotlib.imread` & `matplotlib.pyplot.imshow` to stuff the image into a matplotlib figure may be the most pythonic solution, rather than saving the png direct to disk immediately. 

This would go through the static maps API, if I understand correctly. The patch I'm thinking of is something like:
```python
import matplotlib.image as mpi
import matplotlib.pyplot as plt

...
elif not interactive:
    raw_data = mpi.imread('static_url')
    figure = plt.imshow(raw_data)
    plt.axis('off')
    return figure
```
since `imread` can grab images direct from urls, this would provide a consistent, "pythonic" non-interactive method to handle the maps, I think.

**Comment by andy-esch** [comment]
We're going to default to what happens with matplotlib, seaborn, etc.: return axis objects and let the matplotlib backend (if it exists) do what it does. See more here to test that we're doing things correctly: https://github.com/CartoDB/cartoframes/issues/248
