### ISSUE TITLE
Add defaults to visualization API

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#1430]
After a short conversation with data scientists, let's try to add some default params to the Layer class as we had in helpers:
- Add `title` and use it in the legend and popups
- Add `description` and use it in the legend
- Add `footer` and use it in the legend
- Bring helper default titles to widgets (Categories, Distribution, etc)
- Try to add default_legend and default_widget components so the user doesn't need to know which one to use to override params

**Comment by makella** [comment]
Just want to comment here too with my two cents :)

Since a style **packages** a Legend, Popup and the option for a Widget, I feel like we should have those parameters in the style, not Layer. If you overwrite with custom Legend, Popup, etc. we will ignore, but since these are in essence part of the default you get _with a style_ I feel that you should be able to assign the titles, descriptions, footers inside there vs. the Layer. 

for example, could we go back to this pattern?
```
Map(
    Layer(
        'commercial_burglary_2',
        color_category_style(
            'day_of_week',
            size=10,
            stroke_width=1,
            stroke_color='blue',
            opacity=0.5,
            title='Day of the Week',
            description='description',
            footer='footer'
        )
    )
) 
```

If a user did something like this, we would ignore the title for the Legend, still keep the description and footer for the Legend, and keep the title defined in the style for the Popup:

```
Map(
    Layer(
        'commercial_burglary_2',
        color_category_style(
            'day_of_week',
            size=10,
            stroke_width=1,
            stroke_color='blue',
            opacity=0.5,
            title='Day of the Week',
            description='my description',
            footer='my footer'
        ),
        legends=color_category_legend(title='My Custom Legend Title'),
    )
)  
```

**Comment by cmongut** [comment]
I see your point but `title`, `description` and `footer` don't seem style params but content ones.

**Comment by makella** [comment]
but they are packaged with a style... it is like changing the color or size of points in my opinion! and directly tied to the styling on the map!

**Comment by makella** [comment]
the other thing we could discuss then is only providing a legend with a style and at a minimum being able to modify the title, description, footer removing the options for widgets and popups. what if someone just wants to use helpers like they were originally meant? to quickly create a map and be able to publish... a legend is a key piece of that more than popups and widgets IMO
