### ISSUE TITLE
Gather usage metrics

### ISSUE THREAD

**Issue by ilbambino** [CartoDB/cartoframes#1457]
From product perspective we would like to understand how users are using CartoFrames. In order to be able to do it, we would like to instrument the package with some metrics. There are some important points to take into account regarding the metrics:

- There should not collect any of the data users are analysing with CartoFrames
- It should be possible to disable them (if the user decides it so)
- We need to add them into the doc and probably license.
- They should be transparent to the user. If they fail, there is an error or whatever they cannot interfere with the normal usage.

The things we want to measure are:

- Map creations
- Upload data
- Download data

The idea is to have a metrics endpoint in our platform where we can make a `POST` request with a _JSON_ with the payload of the metric. The payload will be something like:

```json
{
  "cf_user_id": "some UUID generated and unique per install",
  "user_id": "can we get the user_ID from CARTO if they have logged in? OPTIONAL",
  "event_name": "the_event_name",
  "event_source": "cartoframes",
  "source_version": "v1.0",
  "event_version": 1,
  "event_time": "RFC3339 Time",
  "extra_field_1": "whatever",
  "some_other_field": 2323
}
```

The fields:

- `event_name` is in the form `object_action` so it would be `data_uploaded`.
- `cf_user_id` we would need to generate something that is constant through the use of the library. But it cannot be PII. Some UUID and stored somewhere, a hash of some machine identifier…
- `event_source` fixed to `cartoframes`
- `source_version`  the version of CartoFrames.
- `event_version` at this point 1. If we ever change the format of the payload we will bump the number.
- `event_time` the time when the event was generated. RFC3339 format
- any other extra field needed in the form of key/value pairs to add context to the event.

**Comment by Jesus89** [comment]
Hi @ilbambino. Thanks for the detailed description :) I comment my thoughts about how to obtain the data and some suggestions:

- `cf_user_id`: I would rename this to `installation_id` or something like that. My idea is to get the `user_config_dir` and save a file `uuid` with a randomly generated id. This will be created, if not exists when `cartoframes` is used.
- `user_id`: We can use the `username` since the user runs operations like publish, download or upload.
- `event_name`: Are the options `data_uploaded`, `data_downloaded`, `map_published`?
- `source_version`: we can get this from `cartoframes.__version__`.
- `event_version`: I would change the type to string.
- `event_time`: I would rename this to `event_timestamp`.

So an example could be like:

```json
{
  "event_version": "1",
  "event_timestamp": "1578917205000",
  "event_source": "cartoframes",
  "event_name": "data_uploaded",
  "source_version": "1.0.0",
  "user_id": "carto-user",
  "installation_id": "18bfb88a-e040-4f4f-80c1-1ef2a795603a"
}
```

About the API to configure the metrics, I would add a new method into `utils`.

```python
from cartoframes.utils import config_metrics

config_metrics(enable=False)
# or config_metrics(disable=True)
```

In order to persist this information, we must write another file in `user_config_dir`. We can create a file called `metrics` to store both the uuid and the flag.

What do you think?

**Comment by ilbambino** [comment]
Thank you! I agree with the approach with some comments:

- `user_id`. Let's not implement it yet. We don't want to send the username for privacy/legal reasons. We need to find another solution.
- `installation_id` looks like a great approach. The only caveat would be in environments like Google Colab. In those cases the persistence might not be there all the time. For those it would be great (not mandatory for 1st if we cannot get there) to have a new field `running_env` and put there `colab` if we can detect that is the environment we are running on.
