### ISSUE TITLE
Named maps handling

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartoframes#205]
I see that named maps are used to show the embedded maps.  I'd rather see us using [anonymous maps](https://carto.com/docs/carto-engine/maps-api/anonymous-maps/).

The advantage to this, is that we don't create named maps, which is a limited resource for some users with a lot of data (since there is one named map per dataset and per map). The limitation of using anonymous maps, is that they are only valid for two hours, after which, you have to regenerate them. But I think that fits pretty well for the cartoframes usage.

cc @andy-esch @stuartlynn

**Comment by javitonino** [comment]
As a bonus, I saw some comments regarding basemap URLs not being supported. Can you explain a bit what is the limitation? I do not understand if this is a cartoframes limitation or a windshaft one (which it shouldn't, since CARTO supports custom URLs in basemaps).

**Comment by andy-esch** [comment]
The original idea for using the Named Maps API was to allow for live API calls to images embedded in the notebook. The scope of this has changed and we're now saving the images in the notebook to show the current state of the image instead of whatever state is loaded if someone opens the notebook in the future. So using the Anon maps API sounds like it would be ideal now.

The TODOs we had with the basemap URL were that we wanted to only use one named map template for any type of one-layer map. Named maps don't allow for templating of basemap URL (or other properties outside of SQL and CartoCSS). We requested more general templating here: https://github.com/CartoDB/Windshaft-cartodb/issues/697

**Comment by javitonino** [comment]
Oh, now it all makes sense. Thanks for the explanation.

**Comment by andy-esch** [comment]
@javitonino, can you point to some examples of using anonymous maps that are authenticated (api key) for both static and interactive/carto.js maps?

**Comment by javitonino** [comment]
There is some information here:
https://carto.com/docs/carto-engine/maps-api/anonymous-maps/

Full example:
With this mapconfig:
```json
{
  "version": "1.3.0",
  "layers": [{
    "type": "mapnik",
    "options": {
      "cartocss_version": "2.1.1",
      "cartocss": "#layer { polygon-fill: #F00; }",
      "sql": "select * from laspalmas"
    }
  }]
}
```

```sh
curl -X POST https://javitonino.carto.com/api/v1/map?api_key=XXX -H 'Content-Type: application/json' -d @config
```

```json
{
    "layergroupid": "e93018f5a9e649c4f15de972c48f81be:1503650119071",
    "metadata": {
        "layers": [
            {
                "type": "mapnik",
                "id": "layer0",
                "meta": {
                    "cartocss": "#layer { polygon-fill: #F00; }",
                    "stats": {
                        "estimatedFeatureCount": 34
                    },
                    "cartocss_meta": {
                        "rules": []
                    }
                }
            }
        ],
        "dataviews": {},
        "analyses": []
    },
    "cdn_url": {
        "templates": {
            "http": {
                "url": "http://{s}.ashbu.cartocdn.com",
                "subdomains": [
                    "0",
                    "1",
                    "2",
                    "3"
                ]
            },
            "https": {
                "url": "https://cartocdn-ashbu_{s}.global.ssl.fastly.net",
                "subdomains": [
                    "a",
                    "b",
                    "c",
                    "d"
                ]
            }
        },
        "http": "ashbu.cartocdn.com",
        "https": "cartocdn-ashbu.global.ssl.fastly.net"
    },
    "last_updated": "2017-08-25T08:35:19.071Z"
}
```

Then it's exactly the same as with named maps.

To get a static image:
`https://javitonino.carto.com/api/v1/map/static/center/e93018f5a9e649c4f15de972c48f81be:1503650119071/6/29/-15/200/200.png?api_key=XXX`

Or an interactive map, use a vizjson like so: https://gist.github.com/javitonino/742afe514ce22d846e0762fe23f4f295

Something important to note is that I thought that you could pass the layergroupid directly to cartodb.js for rendering, but it seems that I was completely mistaken, you need to either pass a named map template or a vizjson + api_key. There is another trick, which is to treat the anonymous map as a tiled layer, but it also needs the api key, and we lose the opportunity to add legends/tooltips, etc.

So, sorry for misleading you, I really thought that anonymous maps were usable. After this, maybe it's not such a great idea then to do this, since the api_key would be in the generated HTML. 🤔

**Comment by andy-esch** [comment]
The API key in the carto.js app is another reason we went to named maps.. I forgot until you wrote it now.

Do you think having the ability to create carto.js maps with a template id would be a feature request that could end up in the code base?

I'd love to have a parallel approach to map making between static and interactive maps. Anonymous maps are much more flexible than named maps, and I love the idea of their temporal nature. Named maps are very hard to deal with in a general way since templating is only allowed on queries and styling.

**Comment by javitonino** [comment]
> Do you think having the ability to create carto.js maps with a template id would be a feature request that could end up in the code base?

I'd like to see it since, as you say, it offers great flexibility for short-lived maps. For me it's hard to say, but I'm guessing it's unlikely, since I don't think it's a very common use case. Maybe engine people have a clearer idea.

**Comment by andy-esch** [comment]
We're going to deprecate named maps in cartoframes if we add raster support in the v1.0+
