### ISSUE TITLE
Wishlist: is it possible to have more basemap options?

### ISSUE THREAD

**Issue by iamwfx** [CartoDB/cartoframes#226]
Specifically: is there a way to use basemaps from mapbox XYZ urls? :)

**Comment by andy-esch** [comment]
Eventually, yes :) Right now we're constrained by how we implement the map creation. It turns out to be pretty tricky to get all of cartoframes' map making constraints into a single workflow.

Short answer is: yes it's possible. Longer answer is that it will be implemented eventually, but we have to do some re-architecturing of the internals. Named maps can't template everything (https://github.com/CartoDB/Windshaft-cartodb/issues/697) and are a limited resource. So we need to figure out how to leverage anonymous maps in some cases and named maps in others (see ticket here: https://github.com/CartoDB/cartoframes/issues/205). Besides having any basemap under the sun, we need to add interactivity like tooltips!

**Comment by andy-esch** [comment]
Using `vector.vmap([vector.Layer('tablename'), ], context=cc, basemap={'style': 'mapbox map specifier', 'token': 'mapbox token')` you can use any mapbox map. You can also pass in any other style that will work with mapbox gl.

I don't see us being able to add generic basemaps to `cc.map` in the near term.

**Comment by andy-esch** [comment]
Closing as it's supported in VL! Not sure if raster maps will ever get this functionality.

**Comment by maptastik** [comment]
Is there any chance this issue will be revisited? From what I can tell, XYZ tiles are not supported in CARTOframes. Apologies if I ammisunderstanding, but it appears we are limited to either:

1. CARTO basemaps as provided via `basemaps`
2. Mapbox vector tiles

I'd like to be able to use imagery served as XYZ tile as a basemap for some of my work,. However, my understanding is one would need to publish that imagery as Mapbox vector tiles and serve them from a  vector tile server (e.g. Mapbox, OpenMapTiles, custom). While this is all certainly possible, it adds quite a bit of friction in circumstances where an XYZ tileset has already been published and is maintained by a third party.

Reading through this issue, I appreciate that this is not a simple matter of simple of exposing a `url` parameter, but now that v1.x has been out for a bit, I'm curious if XYZ tile support is something that would be considered again.

**Comment by Jesus89** [comment]
Hi @maptastik.

You're right. Now only CARTO or Mapbox basemaps are available. FYI we are working on a new Web SDK which will be used by CARTOframes to render maps in the next mid-term version (https://github.com/CartoDB/toolkit). This will change everything regarding rendering internally, so it opens the option to allow XYZ tile support, and we will consider your request.

Thanks.
