### ISSUE TITLE
Add url param to monitor cartoframes usage

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/cartoframes#238]
On calls to the SQL, Maps and Import api we should append a url parameter like &cartoframes=v1.2 or something similar to be able to have metrics on adoption/usage.

**Comment by andy-esch** [comment]
Sounds good, I'll start mapping out the places where this will be added.
One problem I see is that some methods, like map creation, use various services multiple times to gather information like geometry type, schema, etc. so that it can construct appropriate cartocss defaults. In the worst case, it might hit the APIs a half dozen times.

**Comment by stuartlynn** [comment]
Hey. 

So at least for the SQL API, if we add ```client=cf-${version}``` as a URL param. We should be able to track the usage using google analytics

**Comment by andy-esch** [comment]
Currently cartoframes uses the SQL API to give a representation of the usage of each method. I'm closing this until more granular information is requested. Handled in #256
