### ISSUE TITLE
Error when re-running cc.map() with a torque layer

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#249]
Problem: Re-running a cell that contains a cc.map() function with a torque layer produces the following error message:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-5c8e229f7966> in <module>()
----> 1 cc.map(layers=torque_layer)

~/proj/cartoframes/cartoframes/context.py in map(self, layers, interactive, zoom, lat, lng, size, ax)
    834                 layer.cartocss = json.loads(
    835                         resp.text.split('&& cartoframes(')[1]
--> 836                             .strip(');'))['metadata']['layers'][1]['meta']['cartocss']
    837                 config.update({
    838                     'order': 1,

KeyError: 'metadata'
```
Where
```
torque_layer =  Layer('all_month_3',
                     time = {'column':'time', 'method':'sum', 'trails':4, 'duration':60},
                     color = {'column':'mag','scheme':styling.sunset(3)})
```

**Comment by andy-esch** [comment]
I'm having trouble reproducing. I wonder if the fetching of the processed Turbo-Carto CartoCSS returned an error. There's currently no error catching depending on the responses of that API call: 
https://github.com/CartoDB/cartoframes/blob/c70b94ee7e0dea6e4e973d246b2a1b8904ed57fc/cartoframes/context.py#L843-L852

We should probably wrap that `requests.get` in a try / except block and do a `resp.raise_for_status()` on the response. 

Another important thing worth investigating here is whether we can avoid getting the response back as a JSONP, as this is not a convenient type in Python (which is why we have to do that string split and cast to a `dict`). JSON responses would be preferred.

**Comment by michellemho** [comment]
https://github.com/CartoDB/cartoframes/pull/257
