### ISSUE TITLE
wrong credentials needs better error or test

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartoframes#275]
Trying to use a wrong username and api_key credential returns the following error when trying to write a dataframe:

`JSONDecodeError: Expecting value: line 1 column 2 (char 1)`

The error should be more specific. I believe we're getting something like a 404 missing page or an error message that simply says "an API key must be provided", and the JSON decoding isn't expecting this.

We could maybe add a test when the CartoContext class gets instantiated to make sure it's a valid username and API key combination?

**Comment by andy-esch** [comment]
Yep, I agree that more is needed there. I'm open to ideas on how best to do this.

**Comment by andy-esch** [comment]
This used to work better because `CartoContext(...)` has an internal SQL API call `self.sql_client.send('show search_path')` that was a POST (therefore requiring authentication), but now it's a GET only, which we'd like to keep for monitoring purposes.

One option could be to see if the carto python sdk's `APIAuthClient` class has validation of credentials. Another idea is to send a bare-bones API call that requires authentication when CartoContext is instantiated.
