### ISSUE TITLE
Save dataframe index as cartodb_id

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartoframes#580]
If I'm not wrong this is something that was working in the `0.9.2` version of CARTOframes. 

The dataframe index was being saved as cartodb_id and then used as the index when reading from CARTO to a dataframe as well.

Do we still want this to work in the same way in the `new` versions?

cc. @andy-esch

**Comment by andy-esch** [comment]
Can you give an example of it not working? I haven't seen it not setting the `cartodb_id` as the index if that column is present in a query.

This is set in: https://github.com/CartoDB/cartoframes/blob/master/cartoframes/context.py#L865-L866

**Comment by alrocar** [comment]
mmm I guess I was wrong...

I was understanding the dataframe index was being saved as the `cartodb_id` column, but looks like it's not:

```
DataFrame indexes are changed to ordinary columns. CARTO creates
            an index called `cartodb_id` for every table that runs from 1 to
            the length of the DataFrame.
```

So the dataframe index column is just saved as a regular column and cartodb_id is a sequential index. Then on `read` the dataframe index is set to `cartodb_id`

Is that right? ^

**Comment by andy-esch** [comment]
Yep, that's correct from what I remember. An exception is that the dataframe index is only written to carto if it is not the default (e.g., if it's not `RangeIndex(start=0, stop=N, step=1)`). It's discarded if it's the `RangeIndex(start=0, stop=2, step=1)` because that's usually just a remnant of loading from a csv using `pd.read_csv` or something like that. 

To illustrate the flow.
1. Start with a dataframe with columns: [`col1`, `col2`] with a default RangeIndex
2. write to carto, now table has [`col1`, `col2`, `the_geom`, `cartodb_id`, `the_geom_webmercator`]
3. read from carto, dataframe has: [`col1`, `col2`, `the_geom`] and index [`cartodb_id`]

If 3 is written to carto and read back, it should be indentical.

**Comment by andy-esch** [comment]
I played with the idea of setting the df index to be the cartodb_id, but df indexes can be any type, and can be negative numbers, etc. cartodb_id should be natural numbers, although they can be integers in general. Either way, it's not worth doing something automagically.

**Comment by alrocar** [comment]
_Either way, it's not worth doing something automagically._

OK that was my next question. So then we'll make sure to stick to the behaviour you mentioned.

Thanks!

**Comment by alrocar** [comment]
Fix this test `test_cartocontext_write_index`

- Upload `df.index` as a column
- Keep `cartodb_id` as index
