### ISSUE TITLE
Change Layer API

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#615]
Related with https://github.com/CartoDB/cartoframes/pull/586

Context
=== 
We want to change how we currently use the different layers we have:

* `QueryLayer`
* `LocalLayer`
* `Layer`

First Approach
===

We've thought the following solution as a starting point to address this issue. We (_backend team_) are already working on a `Dataset` class. This class is going to handle local/remote datasets, but for this issue, I'm going to talk about it as a black box.

Since a `Dataset` is one of the source types we've in CARTO VL, we could have, additionally a `SQL` or `Query` class and a `GeoJSON` class. These clases aren't our priority for this task at this point, but let's just imagine we'll have these _"source"_ classes.

Each layer will have a _source_ class. We'd have a main `Layer` class, that will receive this _source_ class and a **context** (we'll talk later about the contexts).

Then, we'd have three classes that'd inherit from `Layer`: `PointLayer`, `LineLayer` and `PolygonLayer`. What's the advantage of having a class per geometry type? First, that we know at first glance the geometry of the layer. But also, that we could implement specific **helper methods** depending on the geometry, and that'd be very cool.

* Contexts _TBD_

It'd be useful to provide a context per source, so you can combine both local and remote datasets, for instance. By declaring the context in the map, this is the context the layer would use, but you'd be able to use an specific context for a layer.

For example:

```python
vl.Map([
      vl.PointLayer('dataset_1'),
      vl.PolygonLayer('dataset_2')
   ],
   context=context
)
```

```python
vl.Map([
      vl.PointLayer('SELECT * FROM dataset_1 WHERE cat = "cat"'),
      vl.PolygonLayer(vl.GeoJSON('file_name.geojson'))
   ],
   context=context
)
```

To Do
===

> *Note*: Front + Back should be involved in this task

- [x] Refactor base Layer class
- ~Create PointLayer, LineLayer and PolygonLayer~ ❄️ 
- [x] Define how to integrate the Source (_Dataset_)
- [x] Create SQL & GeoJSON sources

Other ToDos moved to https://github.com/CartoDB/cartoframes/issues/629

**Comment by VictorVelarde** [comment]
Some thoughts about this:

> Nomenclature depending on the source: Should we use similar names to the ones we're using in CARTO VL sources? (GeoJSON, MVT, Dataset, SQL...)

I would keep those concepts separated, at least by now. I would vote for having a base 'Layer' with all the style properties + a common 'source' property. And I would definitively promote a 'Source' class with different subclasses depending on the format / origin (GeoJSON, SQL...)

> Nomenclature depending on the geometry type: It'd be useful to know on a first sight more information about the layer geometry. This is useful when having more than one geometry types in the same visualization.

I think we can find other mechanisms for that, without creating more types.

---

Also we're going to have a broader discussion about Layer API, considering other use cases, in an external document

**Comment by VictorVelarde** [comment]
## Status update

After the weekly meeting today:

**Advances**:
- 'style' object & 'variables' API definition (+ examples).
- VL changes / issues related to legends.
- 'Simple / Categorical' legend implemented in Airship (& its Bridge).

**Priorities this week (just 3 days in Spain)**:
- 'develop' branch with: declarative 'style' + 2 legends integration in CF ('Simple / Categorial' and 'Point size').
- analysis about Layer API (Dataset / Source and Layer).
- start a separated discussion about 'Style' helpers.

So, in a few words:
* Airship legends are progressing fine.
* VL style definition works (no helpers).
* We still lack of a common API definition for Layers and Data-sources (back / front), and this is a **key factor**.

cc @jorgesancha and cc @ivanmalagon

**Comment by elenatorro** [comment]
I've updated the description after talking with the people involved in this task :)

- @makella suggested we could have different layers depending on the geometry
- @javitonino explained to me the work that they're doing in the backend side and some thoughts about the API, and he agreed it would be great to have different layer per geometry so we could have specific style helpers depending on the geometry ✨ 
- This is related to what @andy-esch and @makella also said about having style helpers, and I think it's a very good solutions.
- Having different sources is what @VictorVelarde suggests about the `source` class in the previous comment.

Although this task is not a priority for the current epic, I think this is a good starting point, because all of the pieces begin to fall into place.

**Comment by makella** [comment]
@elenatorro this is great. thank you for summarizing all of this for us!!

I think the idea of knowing the geometry to match to helper methods will be really useful... and it will also give us the ability to have specific names for the helper methods that match them. A good example is choropleth (should only go for PolygonLayer) whereas the same ramp would be used for points, but we'd call that classed color (or something).

Just to make sure I understand, 
- Layer classes would be one of: `PointLayer, PolygonLayer, LinesLayer`
- and then each class can also have a different source: dataset, sql, geojson, mvt, ....

```
vl.Map([
      vl.PointLayer('SELECT * FROM dataset_1 WHERE cat = "cat"'),
      vl.PolygonLayer(vl.GeoJSON('file_name.geojson'))
   ],
   context=context
)
```
In the example above, the geojson polygon source seems a little verbose to me, but I get why it is like that. Might be a silly question, but could we detect that it is a geojson simply looking at the source name? For example:

`vl.PolygonLayer('file_name.geojson')`

**Comment by elenatorro** [comment]
> A good example is choropleth (should only go for PolygonLayer) whereas the same ramp would be used for points

Exactly, @javitonino used the same example, great minds think alike.

> the geojson polygon source seems a little verbose to me

I agree, it'd be good to have something "smarter"

**Comment by VictorVelarde** [comment]
I've had some doubts, but I'm ok with using the 'geometry' type, if you all see a clear value on it.

And I'm specially keen on the idea of `Layer = Source + Style + { Extras }`, being 'Extras' a set of optional parameters such as 'Interactivity', 'Variables' and probably 'Legend' definition.

Regarding to verbosity, I think that now it's better to be explicit and work with Classes, not strings, and later on to improve on that (overloading methods for those smart 'source-type detections' if it is required). Also, we should probably think about 'source' factory methods, such as `Dataset.from_geojson` (in the spirit of `Dataset.from_table`  proposed from backend people).

**Comment by andy-esch** [comment]
I feel hesitant about adding layers by geometry type. I like the transparency aspect of it and the education about cartography, but it also feels like another barrier in getting a map / another thing to learn. Mamata, I understand if you don't want to talk to me again.

We can still educate the user about appropriate methods if we have a single `Layer` type. If `Dataset` is a point layer and a user tries to do something like this:

```python
point_data = Dataset.from_table('earthquakes', cc)
vl.Map([
    vl.Layer(point_data, style=choropleth('mag'))
])
```
Then we can internally check the geometry of `point_data` and give a warning that choropleths are meant for polygon sources, and we suggest using styling helper `abc123` instead.

But besides the styling methods tied to the geometry types and the transparency in the geometry source, I'm still not convinced this is a big win for the API design.

**Comment by VictorVelarde** [comment]
Hi @elenatorro @makella 

If @andy-esch also doesn't see this as something mandatory now for the API, IMO we should postpone the creation of those geom-subtypes.

I would vote for keeping it simple now, with just one *Layer* class, and add the geometry-subtype in the future if it is really required. Going forward that way would be much easier than adding 3 subtypes now and removing them in the future. Also there might be some use cases in which the geom-type is unknown upfront (eg. a 'cities' layer, which could be a point or polygon layer, or a 'river' layer being a line vs a polygon at bigger scale).

I like the idea of throwing warnings or errors if certain combinations are not allowed (because they are cartographically wrong). But that is probably more related to validations inside those extra 'style' / 'layer' helpers than to the Layer type itself.

Regarding to the rest of the Layer API 'changes' described in this issue, I think we should focus on the **Sources**, so that we decided if:
- `vector.QueryLayer` turns into a `Layer` + a vector (CARTO)`SQLSource` and
- `vector.LocalLayer` turns into something like `Layer` + a different set of 'sources' (for now just 'local' ones), starting with:
  - `dataframe`
  - `GeoJSON`
  -  and we could add different 'connectors' in the future (in the form of new data-'sources', eg. CSV), without affecting the basic vector Layer class.

And of course we have to check if the previous fits the current 'Dataset' implementation made by backend supporting the new long-running queries and so on

**Comment by makella** [comment]
> I would vote for keeping it simple now, with just one Layer class, and add the geometry-subtype in the future if it is really required.

Would like to hear @elenatorro's thoughts, but for me, this is a good idea to keep it simple for now and expand in the future... and @andy-esch haha, yesss, i'm still talking to you ;)


> vector.QueryLayer turns into a Layer + a vector (CARTO)SQLSource and
vector.LocalLayer turns into something like Layer + a different set of 'sources' (for now just 'local' ones), starting with:
dataframe
GeoJSON

don't have much of an opinion here but i like the idea of being straightforward. just to clarify, what is the `dataframe` source? a derivative dataset of an operation performed inside of the notebook?

**Comment by elenatorro** [comment]
> what is the dataframe source?

From [CARTOFrames documentation](https://cartoframes.readthedocs.io/en/stable/contrib.html), it's a GeoDataFrame --> http://geopandas.org/reference/geopandas.GeoDataFrame.html

> keep it simple for now and expand in the future

I'm ok with this, let's freeze `Create PointLayer, LineLayer and PolygonLayer` for now. Just pointing that these layers would be a _syntax sugar_ for the `Layer` class, they wouldn't require a lot of extra implementation.

**Comment by andy-esch** [comment]
I'm on board for creating GeoJSON, SQL, and Dataset. For the source that's a GeoDataFrame, what do you suggest for a name? If we call it `DataFrame`, that's confusing w/r/t whether it's a GeoPandas DataFrame or a pandas DataFrame. And that's different from it being a source. Besides that, we'd get name conflicts because importing like this is common: `from pandas import DataFrame`.

I'll continue to think about it. Part of me wants to have `Source` as part of the name to indicate what it is. For example, `SQL` could be many things.

**Comment by elenatorro** [comment]
>  to have Source as part of the name to indicate what it is.

I like the idea of including the `source` keyword. What about having a namespace for the sources? And then for the DataFrame, just `vl.GeoDataFrame` 

```python
vl.source.SQL
vl.source.GeoJSON
vl.source.Dataset
vl.GeoDataFrame
```

Does it make sense?

Naming it `vl.SourceSQL` or `vl.SQLSource` also works for me, just adding this suggestion for discussion :)

**Comment by elenatorro** [comment]
About the `from_geojson` and `from_table` methods, I don't get very well the idea. From my perspective, by default a `Dataset` source is always going to get the data from a CARTO dataset and a GeoJSON will always get a json (in the last implementation, you can pass a GeoJSON source a GeoDataFrame or a string, being the string the name of the GeoJSON file you want to use.

**Comment by oleurud** [comment]
My ideas after reading the thead (I just return from vacation, maybe I say something stupid).

- About sources:

I would talk about `Source` or `Dataset`, regardless of where it comes from (query, a CARTO table or a GeoJSON). Why? From the user point of view, I see the `Source` or `Dataset` as a local Dataframe, I don't mind if the data comes from local or remote, it is a local DataFrame to play with it in a notebook.

In order to create the local DataFrame, I would encapsulate the different logics (query, a CARTO table or a GeoJSON) behind some static methods, as the existing `Dataset.create_from_query()` static method.

And if after playing with the local DataFrame, I want to save it into CARTO, I will use the `Dataset.upload()` method in anycase

- About layers:

Following the same idea, trying to make it simple (and as you said before), I would have only 1 Layer class. If needed in the future, we could convert it into a Factory the really returns a PointLayer, LineLayer or PolygonLayer, but from the user point of view, only the Layer class exists.

- About contexts:

Right now, we are thinking about local and remote (username and apikey), but we could need more like the Analysis Framework one. Following the same idea, from the user point of view, I would like to have only 1 Context class (if I set the username and apikey is remote if not it will be local), but it doesn't seem possible to add more types in the future.

**Comment by oleurud** [comment]
After the yesterday talk, @elenatorro and I have talked and we thought there are 2 different tasks/parts in this issue:
- the VL way: the user has the data ready in the database or in a geoJSON/mvt file and the user wants to render a map with `vl.source.SQL`, `vl.source.GeoJSON`, ...
- the dataframe way: the user wants to make things over the data (using Pandas) and then render a map with the data. To do this, we have 2 options:
  - the user makes over the data (pandas or others ways), then upload the data to CARTO and finally use the `VL way` to render the map. To do this, if I am not wrong, we don't have to integrate anything between backend and frontend.
  - the user makes things over the data (pandas) and then the user has a way to send the pandas.DataFrame to VL. To do this, we have to integrate backend and frontend. The yestarday proposal was talking about this case, because I think having a full local way to render a map is powerful. I want to talk about it with @javitonino & @alrocar about this full local way. But of course, any feedback is welcome.
