### ISSUE TITLE
Add center and zoom information to map

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#631]
As discussed in yesterday's meeting, we should provide the center and zoom on each map so users can easily overwrite the viewport settings during their workflow.

**Comment by andy-esch** [comment]
This is done in `CartoContext.map` (code quoted below). The goal is to have something that's copy-and-paste-able so that it can be directly input into the command args of the map function.

HTML: https://github.com/CartoDB/cartoframes/blob/c94238a545f3dec45963dac3892540942b6f0df8/cartoframes/assets/cartoframes.html#L29-L32
JS: https://github.com/CartoDB/cartoframes/blob/c94238a545f3dec45963dac3892540942b6f0df8/cartoframes/assets/cartoframes.html#L60-L64

workflow:
![mapdata](https://user-images.githubusercontent.com/1041056/56980803-54be7d00-6b4b-11e9-9322-edd0b6a4e264.gif)

**Comment by andy-esch** [comment]
cc @elenatorro

**Comment by Lady-Aga** [comment]
If we are planning to have collapsed legends and widgets in the future and the map center information has to be always visible, I'm a bit worried about having too many panels floating there (legends + widgets + map centers). 
If the widgets weren't collapsed, the "Home" icon and map center information could be on top of the widgets (?).

**Comment by makella** [comment]
@Lady-Aga does it make sense to keep the map center and zoom text fixed? 

In @andy-esch's example above the information is in the top right. On the CARTO VL editor, we put it in the bottom left in line with the carto/basemap info which I think will be less of an issue for the other components that you mention:

<img width="1109" alt="Screen Shot 2019-05-03 at 7 45 52 AM" src="https://user-images.githubusercontent.com/1566273/57141551-b19e7b00-6d77-11e9-9050-07bd9874b9fd.png">

**Comment by andy-esch** [comment]
+1 mamata, I like how it is on the carto vl editor because its set back in a similar way the attributions are set back.

I'm also curious if we could just have it as a new type of cartoframes-specific histogram instead? Not sure if I like this idea, but wanted to see what others think.

**Comment by Jesus89** [comment]
Closed #701
