### ISSUE TITLE
[Documentation: Examples] Review and organize examples

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#750]
Context
===

We currently have several [examples](https://github.com/CartoDB/cartoframes/tree/develop/examples), and some of them are **outdated**.

---

We should decide the structure of the examples directory and the content for each notebook. These examples can also be used as "guides", as we can see in some of the notebooks There're many things we can re use, and we could have a similar Notebook structure.

- [x] Review examples
- [x] Define the list of examples we want to have
- [x] Define examples directory structure
         - [x] Quick start
         - [x] Sources
         - [x] Visualization
         - [x] Helper Methods
         - [x] Publishing
- [x] Apply changes

**Comment by makella** [comment]
Brief note first... After discussing with @elenatorro and @Jesus89 we think it would be best to keep the model of other libraries in the Dev Center. Basically, instead of mixing content between versions, just start new documentation for this version. This will also save us a lot of time for public release since we will already have the structure figured out. 

Based on our conversation, and @elenatorro structure above, we decided that creating content with what we already have is the best way to go.

Here is a basic outline of what we are thinking:
**Guides**:
- [ ] Quick start
  - use current quick start as model
  - use Elena's [discovery talk](https://docs.google.com/presentation/d/1YEHRUItEDO1ctGWHZg8z_gEYMZ9DBFefNfQSPmr_9BU/edit#slide=id.g58ac978985_0_303) for this section (~slides 13-21)
  - viewport and basemap example notebook (cartoframes/examples/Set basemap and viewport.ipynb)
- [ ] Sources
  - we have a good basic sources notebook from Jesus here: /examples/debug/API/source.ipynb
  - if we want to add additional information about GeoJSON, we can use Elena's discovery talk (~slides 29-32)
- [ ] Visualization
  - Helper methods parts 1 and 2: 
  /examples/Helper methods: Part 1
  /examples/Helper methods: Part 2
- [ ] Publishing
  - /examples/Publish a visualization (Kuviz).ipynb

**Examples**:
For a first pass, we can keep the same headings as we have for our guides and any relevant example maps from guides can also be cross-posted in the examples section. In addition, as @elenatorro mentioned, going through the /examples/debug folder and bringing over from there, all relevant examples.
- [ ] Quick start
- [ ] Sources
- [ ] Visualization
- [ ] Publishing

**Reference**:
Assuming that Read the docs includes version support, we can link, as we do now, to this versions reference.

Thoughts? @elenatorro @Jesus89 did I miss anything?

**Comment by makella** [comment]
@jorgesancha after putting in more thought and discussing, what do you think of this proposal? Related to https://github.com/CartoDB/cartoframes/issues/755.

**Comment by jorgesancha** [comment]
Looks great! Do you think there will be time for all of this for 0.11, though?

**Comment by elenatorro** [comment]
I think we have time since most of the content is going to be reused. The three sections @makella has mentioned are divided in three issues:

- Guides: https://github.com/CartoDB/cartoframes/issues/755
- Examples: https://github.com/CartoDB/cartoframes/issues/750 (this issue)
- Reference: https://github.com/CartoDB/cartoframes/issues/756

I've just updated the description of each issue with these notes, let's start working on them and, if there's anything we think we can leave out of the scope due to lack of time, we can discuss it 👍

**Comment by jorgesancha** [comment]
Sounds like a plan, @elenatorro, thank you!

**Comment by makella** [comment]
thanks @elenatorro !

**Comment by elenatorro** [comment]
Closing since it's being reviewed in https://github.com/CartoDB/cartoframes/pull/781
