### ISSUE TITLE
Feature request: Specify geometry column name in upload

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#854]
We currently offer `with_lnglat` to create a point geometry from coordinates but we do not offer users a way to establish the geometry column other than forcing them to rename it to `the_geom`, which is maybe an implementation detail too far?

I support adding an additional kwarg `geom_col='the_geom'` that can be overwritten to be another geom column.

I can see some complications with GeoDataFrame vs. DataFrame since GDFs have the `geometry` attribute/name, but overall think this would give users more flexibility / control in their workflows since it doesn't force them to change their dataframes to work with our platform.

**Comment by Jesus89** [comment]
OK. We will prioritize this.

When we visualize a DataFrame this is converted internally to GeoDataFrame and the geometry is automatically detected and decoded.

Maybe we can do something similar for the upload method.

cc @alrocar @oleurud

**Comment by alrocar** [comment]
IIRC, didn't we remove that parameter on purpose in v0.10? << @oleurud 

I'm more in favour of autodetection as (I guess) Jesus is suggesting, something like:

- If the dataframe has one of our supported geometry column names, use that column as `geom_col`.
- Otherwise, get the first non-null value of each column and try to decode it with our supported geometry formats.
- First match is used as the geometry column to upload.

- Best case we detect the geometry column by the name of the column.
- Worst case, we have to process one value of each column to see if it is a geometry column.

Anyway, I'm open to any other suggestion 👼

**Comment by oleurud** [comment]
We are getting only one geometry (cartodbfy only keeps one geometry column). Right now, in CARTOframes the order to get a geometry is:
1. geoDataFrame
2. the_geom column
3. geom column
4. geometry column
5. no geometry

But in the end, I think the source of the problem is to have both approaches: DataFrame with geometries and geoDataframes.

I think we should solve the source problem instead of adding small fixes. We have several issues related with that like this one or https://github.com/CartoDB/cartoframes/issues/1039 and more generic like https://github.com/CartoDB/cartoframes/issues/910

IMO we should go to geoPandas because we are doing a "parallel" version of that and we could make it stronger together.

**Comment by Jesus89** [comment]
This has been already implemented in the 1.0.0 release.

```python
to_carto(df, 'table_name', geom_col='my_geom')
```
