### ISSUE TITLE
Unable to plot

### ISSUE THREAD

**Issue by Alalalalaki** [CartoDB/cartoframes#900]
I am trying the basic use of the package in JupyterLab 1.0. But every cc.map() raise the error `ValueError: list.remove(x): x not in list`

**Comment by andy-esch** [comment]
Could you give us more information so that we can reproduce the error / understand the context better?
* Python version
* Cartoframes version (`from cartoframes.__version__ import __version__; print(__version__)`
* code you are writing to get the error (e.g., 'from cartoframes import CartoContext; cc = ...; cc.map(Layer(...), ...)`??)

**Comment by Alalalalaki** [comment]
@andy-esch 

- Python 3.7.3
- cartoframes 0.10.1
- ![Xnip2019-08-09_22-47-15](https://user-images.githubusercontent.com/31154974/62783579-afc32100-baf7-11e9-92fc-4fac23a65891.jpg)

**Comment by andy-esch** [comment]
Try wrapping your layer in a list:
`layers=[l, ]`

**Comment by Alalalalaki** [comment]
@andy-esch Still not works. And exactly the same error message.

**Comment by andy-esch** [comment]
What matplotlib version are you on?

**Comment by Alalalalaki** [comment]
@andy-esch 3.1.0

**Comment by andy-esch** [comment]
It works for me in a virtual env with python 3.7.3 and matplotlib 3.1.1. I don't use anaconda so cannot easily test. I've seen this same error reported about matplotlib elsewhere though: https://github.com/jakobrunge/tigramite/issues/40#issuecomment-503987227

You could try changing your matplotlib version.

**Comment by andy-esch** [comment]
@Alalalalaki are you still experiencing this issue? It seems that changing your matplotlib version to 3.0 in anaconda will solve the issue.
