### ISSUE TITLE
CI tests are failing

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#944]
Tests are failing in Travis due to Rate Limits (and maybe other issues). This is a blocker because we can't merge any PR into develop unless tests are passing.

i.e: https://travis-ci.org/CartoDB/cartoframes/builds/577767984?utm_source=github_status&utm_medium=notification

**Comment by oleurud** [comment]
In the past, I needed to change the rate limits for testing users, mainly the COPY endpoints ones to 1 req/sec. Yesterday, I have updated them to 3 req/sec (with an initial burst of 10). I don't really know what is happening because it has no sense, we are not making more requests, so we should not need bigger rate limits...

**Comment by elenatorro** [comment]
Fixed!
