### ISSUE TITLE
[Doc - Guides] - Use Location Data Services

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#995]
[EPIC] https://github.com/CartoDB/cartoframes/issues/967

### Introduction:

Data used:
- Filter stores by revenue (for example)

### Consuming Quota

- Check the quota and learn about the `dry_run` option to prevent consuming quota.

## Local Cache

- Explain local cache, and the different use cases: saving or not data locally

## Results: metadata

* Show table with the different fields the `metadata` contains 
* Explain wrong geocoding with precision (status code)
* Visualize precision (status code)

### Isolines Service

- Mention again dry_run option for quota consuming

#### Isodistances

- Example using isodistance service in a subset of stores

#### Isochrones

- Example using isochrone service in a subset of stores

### Conclusion

- Understand the AOI around a subset of stores

**Comment by alrocar** [comment]
About geocoding there are some features that I think we should highlight somehow, since they are clear differentiators to other geocoding libraries. Not sure if in this guide or in any other place... just writing down my thoughts here by now:

1. As part of the geocoding result you get, the `dataframe` and the `metadata`. The `metadata` contains very important information for any spatial analysis. If you geocode addresses and you don't get accurate results, then your complete analysis might be wrong. I think to highlight that, we could filter the geocoded results by a threshold of the relevance in the metadata. 

2. Incremental geocoding. There's a very typical case in which you have a source dataframe, you geocode it (it's stored in your account), and then you add more data or new addresses, whatever... That would be a nice case for incremental geocoding.

Maybe it's a bit forced include those features in the guide, so maybe we just move the examples in the Data services reference to concrete sections in the guides. What do you think?

**Comment by elenatorro** [comment]
Nice feedback! As you said, sometimes there's something that will make the guide more complex and that might be out of the scope, in those cases it's better to link to an external example / reference as you mention.

About 1. I think this should be included in the guide, it's important and I think this is the best place to add it and highlight it.

About 2. Good catch, I didn't know about this use case. My opinion is that we should add an example of incremental geocoding and add the link in the guide.
