### ISSUE TITLE
[Doc - Guides] -  Enrich your Datasets

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#997]
[EPIC] https://github.com/CartoDB/cartoframes/issues/967

**Comment by alrocar** [comment]
Since enrichment explanations can be as comprehensive as we want, so we (@cmongut and I) have decided follow this approach:

### Introduction

Same story as in the quickstart, Starbucks stores + AOI with the goal of calculating the revenue by population, so we need to know the population around that stores.

### Choose variables to enrich

Connects nicely with the Discovery guide, explain how to list the variables of the datasets you have licensed and how to choose the total population one from the AGS demographics dataset.

### Polygon enrichment

A simpler version with just a `geodataframe` stored as a CSV which already contains the AOIs of the Starbucks stores (we'll add a reference to the quickstart to understand how it was generated) and one variable with default aggregation method.

Explain what is happening under the hood

### Points enrichment

A simpler version with the stores and enrich with a non extensive variable, like the population density.

### Advanced concepts

Now that we have explained the basics let's talk about aggregation methods and filters, and an explanation of how they work.

- Aggregation methods
- Variable filters

We can include here some more thorough explanations from the enrichment technical doc done by @arredond 

### Conclusion


cc. @alasarr

**Comment by alasarr** [comment]
Sounds good me. 

Make sure points enrichment is before of polygons, just be sure the easy part is before.
